
public class Test45 {

    public static void main(String[] args) {
        Bankomat bankomat = new Bankomat();
        bankomat.nalozi(36, 546, 574);
        System.out.println(bankomat.dvigni(16, new Datum(7, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(7, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(7, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(13, new Datum(7, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(7, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(8, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(9, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(9, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(3, new Datum(10, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(10, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(11, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(11, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(12, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(13, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(13, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(14, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(15, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(16, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(17, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(17, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(18, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(18, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(13, new Datum(18, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(15, new Datum(19, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(20, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(21, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(13, new Datum(21, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(21, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(21, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(22, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(23, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(24, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(25, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(26, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(27, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(28, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(1, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(2, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(2, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(2, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(3, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(3, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(4, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(5, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(6, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(3, new Datum(6, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(7, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(8, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(9, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(3, new Datum(9, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(9, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(10, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(11, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(12, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(13, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(14, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(14, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(13, new Datum(15, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(16, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(17, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(17, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(18, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(18, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(19, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(20, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(20, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(20, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(21, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(22, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(13, new Datum(22, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(23, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(23, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(13, new Datum(24, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(24, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(24, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(25, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(26, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(15, new Datum(26, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(27, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(27, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(27, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(15, new Datum(27, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(15, new Datum(27, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(28, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(1, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(2, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(2, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(15, new Datum(3, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(4, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(5, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(5, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(5, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(5, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(5, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(5, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(5, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(15, new Datum(5, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(5, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(5, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(6, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(7, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(8, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(9, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(10, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(10, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(11, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(11, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(12, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(12, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(3, new Datum(13, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(14, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(15, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(15, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(16, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(16, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(17, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(18, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(19, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(20, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(3, new Datum(21, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(22, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(22, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(23, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(23, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(24, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(25, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(26, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(27, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(27, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(27, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(27, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(28, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(1, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(2, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(3, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(3, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(4, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(4, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(5, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(5, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(5, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(6, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(15, new Datum(7, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(8, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(8, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(3, new Datum(8, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(8, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(8, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(8, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(8, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(8, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(9, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(10, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(11, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(12, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(12, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(12, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(13, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(14, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(15, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(16, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(17, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(17, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(17, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(17, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(17, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(18, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(15, new Datum(19, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(20, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(21, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(3, new Datum(21, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(21, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(22, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(22, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(23, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(15, new Datum(24, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(24, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(24, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(24, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(25, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(25, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(3, new Datum(25, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(15, new Datum(25, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(25, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(26, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(26, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(27, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(13, new Datum(28, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(1, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(2, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(2, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(3, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(3, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(3, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.najDatum().toString());
    }
}
