
public class Test42 {

    public static void main(String[] args) {
        Bankomat bankomat = new Bankomat();
        bankomat.nalozi(586, 777, 175);
        System.out.println(bankomat.dvigni(11, new Datum(20, 2, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(21, 2, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(27, new Datum(21, 2, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(3, new Datum(22, 2, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(23, 2, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(24, 2, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(24, 2, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(24, new Datum(25, 2, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(33, new Datum(26, 2, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(26, new Datum(27, 2, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(39, new Datum(27, 2, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(28, 2, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(26, new Datum(28, 2, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(37, new Datum(1, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(15, new Datum(2, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(2, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(3, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(4, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(35, new Datum(4, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(36, new Datum(5, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(40, new Datum(6, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(43, new Datum(6, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(28, new Datum(7, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(8, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(8, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(8, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(8, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(9, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(10, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(42, new Datum(11, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(35, new Datum(11, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(26, new Datum(12, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(38, new Datum(12, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(13, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(30, new Datum(14, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(30, new Datum(14, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(31, new Datum(14, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(15, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(30, new Datum(15, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(27, new Datum(15, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(16, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(17, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(38, new Datum(18, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(18, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(27, new Datum(18, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(39, new Datum(18, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(19, new Datum(18, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(19, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(20, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(20, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(42, new Datum(21, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(39, new Datum(22, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(24, new Datum(22, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(34, new Datum(23, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(23, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(45, new Datum(23, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(24, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(27, new Datum(24, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(19, new Datum(25, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(23, new Datum(25, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(26, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(29, new Datum(27, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(21, new Datum(27, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(33, new Datum(28, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(28, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(28, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(28, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(28, 3, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(1, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(1, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(29, new Datum(1, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(45, new Datum(2, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(2, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(3, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(3, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(28, new Datum(4, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(4, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(13, new Datum(4, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(5, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(3, new Datum(6, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(6, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(44, new Datum(6, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(39, new Datum(6, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(7, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(7, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(42, new Datum(7, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(8, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(27, new Datum(9, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(40, new Datum(9, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(30, new Datum(9, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(19, new Datum(10, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(10, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(10, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(25, new Datum(11, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(12, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(12, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(13, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(38, new Datum(14, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(3, new Datum(14, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(32, new Datum(15, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(37, new Datum(15, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(37, new Datum(15, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(16, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(38, new Datum(16, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(16, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(19, new Datum(17, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(17, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(37, new Datum(17, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(25, new Datum(17, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(26, new Datum(17, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(34, new Datum(17, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(17, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(17, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(29, new Datum(18, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(18, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(26, new Datum(19, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(32, new Datum(19, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(19, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(20, new Datum(20, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(21, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(22, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(28, new Datum(22, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(23, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(40, new Datum(23, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(24, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(24, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(25, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(36, new Datum(25, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(26, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(26, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(37, new Datum(26, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(13, new Datum(27, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(29, new Datum(28, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(28, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(43, new Datum(28, 4, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(19, new Datum(1, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(2, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(3, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(45, new Datum(3, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(3, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(26, new Datum(3, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(3, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(3, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(4, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(42, new Datum(4, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(26, new Datum(4, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(4, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(35, new Datum(4, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(29, new Datum(5, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(6, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(43, new Datum(6, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(33, new Datum(6, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(6, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(40, new Datum(7, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(7, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(26, new Datum(8, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(9, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(9, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(29, new Datum(10, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(32, new Datum(10, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(26, new Datum(11, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(12, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(13, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(39, new Datum(13, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(34, new Datum(13, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(21, new Datum(13, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(13, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(35, new Datum(13, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(14, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(14, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(14, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(15, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(31, new Datum(16, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(33, new Datum(17, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(45, new Datum(17, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(18, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(19, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(46, new Datum(19, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(20, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(31, new Datum(20, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(21, new Datum(20, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(43, new Datum(20, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(20, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(43, new Datum(20, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(21, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(25, new Datum(22, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(20, new Datum(23, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(26, new Datum(23, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(34, new Datum(24, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(19, new Datum(24, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(46, new Datum(25, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(26, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(26, new Datum(26, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(27, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(27, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(15, new Datum(27, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(34, new Datum(28, 5, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(1, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(27, new Datum(2, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(46, new Datum(2, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(3, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(3, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(20, new Datum(3, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(4, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(26, new Datum(5, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(6, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(43, new Datum(6, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(19, new Datum(6, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(37, new Datum(7, 6, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.najDatum().toString());
    }
}
