
public class Test43 {

    public static void main(String[] args) {
        Bankomat bankomat = new Bankomat();
        bankomat.nalozi(468, 941, 446);
        System.out.println(bankomat.dvigni(18, new Datum(6, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(7, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(37, new Datum(8, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(8, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(27, new Datum(8, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(42, new Datum(9, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(24, new Datum(10, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(11, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(33, new Datum(11, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(30, new Datum(11, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(11, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(11, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(23, new Datum(12, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(13, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(31, new Datum(14, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(15, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(42, new Datum(16, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(36, new Datum(16, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(36, new Datum(16, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(13, new Datum(16, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(16, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(16, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(17, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(43, new Datum(18, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(27, new Datum(19, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(20, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(35, new Datum(20, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(21, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(20, new Datum(21, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(35, new Datum(21, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(25, new Datum(21, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(24, new Datum(21, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(37, new Datum(21, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(30, new Datum(21, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(24, new Datum(21, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(22, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(23, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(26, new Datum(23, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(24, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(25, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(39, new Datum(26, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(27, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(19, new Datum(28, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(27, new Datum(1, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(39, new Datum(2, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(2, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(3, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(3, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(38, new Datum(4, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(4, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(4, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(5, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(6, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(6, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(7, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(30, new Datum(7, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(26, new Datum(7, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(8, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(32, new Datum(9, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(42, new Datum(9, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(42, new Datum(9, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(45, new Datum(9, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(46, new Datum(10, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(37, new Datum(10, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(10, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(10, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(29, new Datum(10, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(11, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(19, new Datum(12, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(13, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(19, new Datum(14, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(15, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(34, new Datum(16, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(19, new Datum(17, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(38, new Datum(18, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(20, new Datum(19, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(20, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(21, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(44, new Datum(21, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(44, new Datum(21, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(22, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(36, new Datum(22, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(31, new Datum(23, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(24, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(25, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(36, new Datum(25, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(36, new Datum(26, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(26, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(26, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(37, new Datum(26, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(27, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(46, new Datum(28, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(28, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(42, new Datum(1, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(39, new Datum(1, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(29, new Datum(1, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(46, new Datum(2, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(20, new Datum(2, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(40, new Datum(2, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(23, new Datum(3, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(33, new Datum(3, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(4, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(13, new Datum(4, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(43, new Datum(4, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(32, new Datum(5, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(5, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(6, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(31, new Datum(6, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(38, new Datum(7, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(7, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(31, new Datum(8, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(8, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(42, new Datum(8, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(36, new Datum(9, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(43, new Datum(9, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(35, new Datum(9, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(9, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(27, new Datum(9, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(30, new Datum(10, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(10, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(10, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(10, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(23, new Datum(10, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(11, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(36, new Datum(12, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(39, new Datum(13, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(14, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(32, new Datum(15, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(32, new Datum(16, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(17, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(18, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(34, new Datum(18, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(40, new Datum(18, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(15, new Datum(18, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(24, new Datum(19, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(13, new Datum(19, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(20, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(4, new Datum(21, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(22, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(30, new Datum(23, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(37, new Datum(24, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(43, new Datum(24, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(29, new Datum(24, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(39, new Datum(24, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(43, new Datum(25, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(35, new Datum(26, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(35, new Datum(27, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(39, new Datum(27, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(28, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(38, new Datum(28, 12, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(35, new Datum(1, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(27, new Datum(2, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(15, new Datum(3, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(3, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(27, new Datum(4, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(32, new Datum(4, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(3, new Datum(5, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(5, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(5, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(35, new Datum(6, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(34, new Datum(7, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(46, new Datum(8, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(8, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(45, new Datum(8, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(31, new Datum(9, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(9, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(10, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(11, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(34, new Datum(11, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(11, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(11, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(31, new Datum(11, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(44, new Datum(11, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(37, new Datum(12, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(38, new Datum(13, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(13, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(14, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(15, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(20, new Datum(16, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(17, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(12, new Datum(17, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(24, new Datum(17, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(24, new Datum(18, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(33, new Datum(19, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(19, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(26, new Datum(19, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(33, new Datum(19, 1, 2001)));
        bankomat.izpisi();
        System.out.println(bankomat.najDatum().toString());
    }
}
