
public class Test44 {

    public static void main(String[] args) {
        Bankomat bankomat = new Bankomat();
        bankomat.nalozi(855, 762, 424);
        System.out.println(bankomat.dvigni(61, new Datum(24, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(23, new Datum(24, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(30, new Datum(24, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(25, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(62, new Datum(25, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(19, new Datum(26, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(24, new Datum(26, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(59, new Datum(27, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(38, new Datum(27, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(27, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(36, new Datum(28, 7, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(54, new Datum(1, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(24, new Datum(1, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(59, new Datum(1, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(47, new Datum(2, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(2, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(2, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(31, new Datum(2, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(2, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(27, new Datum(3, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(4, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(44, new Datum(4, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(45, new Datum(4, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(45, new Datum(5, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(45, new Datum(6, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(61, new Datum(6, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(25, new Datum(6, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(48, new Datum(6, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(27, new Datum(6, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(35, new Datum(6, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(7, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(56, new Datum(7, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(36, new Datum(7, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(58, new Datum(7, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(15, new Datum(8, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(48, new Datum(9, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(44, new Datum(10, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(11, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(36, new Datum(12, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(12, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(47, new Datum(13, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(3, new Datum(13, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(24, new Datum(14, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(14, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(50, new Datum(14, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(46, new Datum(14, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(58, new Datum(15, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(3, new Datum(15, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(62, new Datum(15, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(52, new Datum(16, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(54, new Datum(16, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(33, new Datum(17, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(20, new Datum(18, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(19, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(24, new Datum(20, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(55, new Datum(21, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(20, new Datum(22, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(50, new Datum(22, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(59, new Datum(23, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(40, new Datum(23, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(52, new Datum(23, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(62, new Datum(24, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(21, new Datum(25, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(42, new Datum(25, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(44, new Datum(25, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(23, new Datum(26, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(13, new Datum(26, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(28, new Datum(26, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(2, new Datum(26, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(27, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(13, new Datum(27, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(27, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(28, new Datum(27, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(31, new Datum(28, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(28, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(28, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(49, new Datum(28, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(28, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(53, new Datum(28, 8, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(55, new Datum(1, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(33, new Datum(2, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(24, new Datum(2, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(48, new Datum(3, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(62, new Datum(4, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(35, new Datum(4, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(20, new Datum(5, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(45, new Datum(6, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(59, new Datum(6, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(7, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(28, new Datum(7, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(52, new Datum(8, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(61, new Datum(9, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(61, new Datum(9, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(41, new Datum(10, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(42, new Datum(11, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(18, new Datum(12, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(53, new Datum(12, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(55, new Datum(13, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(44, new Datum(14, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(35, new Datum(14, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(15, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(43, new Datum(15, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(47, new Datum(16, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(13, new Datum(17, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(51, new Datum(17, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(30, new Datum(18, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(30, new Datum(18, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(36, new Datum(18, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(9, new Datum(19, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(29, new Datum(20, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(29, new Datum(21, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(21, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(27, new Datum(21, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(3, new Datum(22, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(20, new Datum(22, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(23, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(30, new Datum(23, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(24, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(24, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(31, new Datum(24, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(16, new Datum(25, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(40, new Datum(26, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(49, new Datum(27, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(42, new Datum(27, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(27, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(48, new Datum(28, 9, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(46, new Datum(1, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(25, new Datum(1, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(45, new Datum(2, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(43, new Datum(2, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(2, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(47, new Datum(2, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(8, new Datum(3, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(55, new Datum(4, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(13, new Datum(5, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(44, new Datum(5, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(49, new Datum(5, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(10, new Datum(6, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(30, new Datum(6, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(33, new Datum(6, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(22, new Datum(6, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(26, new Datum(6, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(38, new Datum(7, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(34, new Datum(7, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(8, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(8, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(30, new Datum(9, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(34, new Datum(10, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(44, new Datum(11, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(6, new Datum(12, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(30, new Datum(13, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(47, new Datum(14, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(53, new Datum(14, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(3, new Datum(15, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(62, new Datum(16, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(27, new Datum(17, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(43, new Datum(17, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(57, new Datum(17, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(18, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(18, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(25, new Datum(19, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(39, new Datum(20, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(53, new Datum(20, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(21, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(45, new Datum(22, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(11, new Datum(23, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(24, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(47, new Datum(24, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(55, new Datum(24, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(25, new Datum(24, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(33, new Datum(25, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(17, new Datum(25, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(1, new Datum(25, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(44, new Datum(26, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(25, new Datum(27, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(14, new Datum(27, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(5, new Datum(27, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(56, new Datum(27, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(7, new Datum(28, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(54, new Datum(28, 10, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(53, new Datum(1, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(24, new Datum(2, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(28, new Datum(3, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(15, new Datum(4, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(61, new Datum(5, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(49, new Datum(5, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.dvigni(60, new Datum(5, 11, 2000)));
        bankomat.izpisi();
        System.out.println(bankomat.najDatum().toString());
    }
}
